### ISSUE TITLE
Mute 无法自动解除禁言

### ISSUE THREAD

**Issue by yufengya0420** [Tsubasa6848/LLSE-Plugins#2]
- 被禁言后显示当前聊天被禁用，但是没有显示禁言原因，也没显示解禁时间
 - 禁言结束了还是不能发消息
 - 另外建议增加当禁言结束时mc.broadcast的形式发送出来 “xxx的禁言时间已结束”
 
![1682343635564](https://user-images.githubusercontent.com/99462074/234592873-7c04b993-8f64-467b-8471-0bdd1fdb3733.png)

**Comment by Tsubasa6848** [comment]
> 被禁言后显示当前聊天被禁用，但是没有显示禁言原因，也没显示解禁时间，禁言结束了还是不能发消息，另外建议增加当禁言结束时mc.broadcast的形式发送出来 “xxx的禁言时间已结束” ![1682343635564](https://user-images.githubusercontent.com/99462074/234592873-7c04b993-8f64-467b-8471-0bdd1fdb3733.png)

不显示时间和原因是因为之前把监听聊天改成了设置mute的ability，为了兼容称号等插件。
恐怕如果继续沿用js版本难以恢复以前的显示原因和时间。
目前没有计划重构C++版本。

后续更新会加一个配置项，可以选择禁言到底调用LLSE监听器还是调用ability。
如果选择监听器就能正常显示原因和时间，但是会导致和称号插件等不兼容。

**Comment by yufengya0420** [comment]
问题是玩家被禁言了也不知道是什么原因，突然就显示聊天被禁用，有点显得太突兀了，如果有其他方法提示给玩家就好了，试试title？还有就是玩家禁言时间结束了他自己也不知道结没结束，还是得同样加个给玩家禁言时间已到期的提示，既然不能用聊天栏提示的话，标题应该能用吧

**Comment by Tsubasa6848** [comment]
> 问题是玩家被禁言了也不知道是什么原因，突然就显示聊天被禁用，有点显得太突兀了，如果有其他方法提示给玩家就好了，试试title？还有就是玩家禁言时间结束了他自己也不知道结没结束，还是得同样加个给玩家禁言时间已到期的提示，既然不能用聊天栏提示的话，标题应该能用吧

到时候改为被禁言和解除禁言的时候，都给一次通知。
LLSE在setAbility之后，会发送updateAbilityPacket，之后无法说话这边是客户端行为，无法直接监听。
